version: '3.7'
services:
  fastapp:
    image: fastapp:latest
    hostname: fastapp
    container_name: fastapp
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai # 设置容器时区
      - LOG_LEVEL=success # 设置日志级别默认debug [info error success]
      # 部署是设置env
      #- MYSQL_HOST=127.0.0.1
      #- MYSQL_PORT=3306
      #- MYSQL_USER=root
      #- MYSQL_PASS=root
    ports:
      - 8000:8000

